# netlify.toml

[build]
  # Perintah untuk membangun proyek Anda (sesuai log deployment)
  command = "bun run build" 
  
  # Direktori output hasil build Vite
  publish = "dist"

[functions]
  # Direktori tempat fungsi Netlify Anda berada
  directory = "netlify/functions"

# Tingkatkan timeout untuk fungsi explore_gemini
[functions."explore_gemini"]
  timeout = 25

# Jadwalkan fungsi fetch-medical-news untuk berjalan setiap 10 jam
[functions."fetch-medical-news"]
  schedule = "0 */10 * * *"

# Konfigurasi untuk netlify dev
[dev]
  # Port tempat framework (Vite) berjalan
  targetPort = 8080
  # Explicitly set framework to avoid detection issues
  framework = "vite"
  # Port yang akan diekspos oleh Netlify Dev (opsional, bisa di-override dengan -p)
  # port = 8888

# Redirects/Rewrites untuk SPA
# Redirect for chatgpt-worker
[[redirects]]
  from = "/api/chatgpt-worker/*"
  to = "https://chatgpt-worker.daivanfebrijuansetiya.workers.dev/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
